### PR TITLE
Contact page added

### LINKED ISSUE #1: Contact Page
Add a good Contact Page.

### PR DESCRIPTION
**Pull request by Mannxxx**
# Fixes Issue🛠️

Closes #1 

# Description👨‍💻 

Added contact page. I've created a new index file for the contacts page in "contact" folder.
I've imported the exact footer and header sections from the app's original index file. I've commented on where script.js and style.css are used. (Make sure to mention the correct paths while testing.)

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
image

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Include the contact folder in the folder assets and give the path of original style.css and script.js file using dots(../..).
Also link this contact page to the Contact Button present in main index.html file. @Mannxxx

**Comment by Mannxxx** [comment]
@Rakesh9100 , Could you check it now? 

- [x] I've added a contact folder in assets folder. 
- [x] Inside contact folder, I've created `contact.html`,` contact.css`, `contact.js`.
- [x] In `contact.js` file, I've linked `style.css` and `script.js` from main directory.
- [x] I've added link to `contact.html` in main `index.html`

**Comment by Rakesh9100** [comment]
Don't put the contact folder inside the images folder. It should just be under the assets folder @Mannxxx 

Also, there should not be any space below the footer.

image

The navbar components of contact page should be functional when clicked on Home and Calculators @Mannxxx

**Comment by Mannxxx** [comment]
@Rakesh9100 , Now see?

**Comment by Rakesh9100** [comment]
Looks fine!! Congrats on getting your PR merged to this repo under Opencode23 🎉🎉 @Mannxxx

**Comment by Rakesh9100** [comment]
Can you comment `Claim` on issue of this PR so that I can assign you there as it is completed @Mannxxx

**Comment by Mannxxx** [comment]
> Include the contact folder in the folder assets and give the path of original style.css and script.js file using dots(../..).
> Also link this contact page to the Contact Button present in main index.html file. @Mannxxx 

    Claim

**Comment by Rakesh9100** [comment]
Do comment on the issue of this PR that is issue number 1 @Mannxxx

**Comment by Mannxxx** [comment]
Issue #1 

Completed, added contact page

**Comment by Rakesh9100** [comment]
Go here <https://github.com/opencodeiiita/CalcDiverse/issues/1> and comment!!

**Pull request merged**
