### PR TITLE
BMI Calculator 

### LINKED ISSUE #3: BMI Calculator
Add a Calculator that calculates the Body Mass Index of a person.

### PR DESCRIPTION
**Pull request by Mannxxx**
# Fixes Issue🛠️

Closes #3 

# Description👨‍💻 
Added BMIcalculator. I've imported the exact footer and header sections from the app's original index file. I've commented on where original script.js and style.css are used. (Make sure to mention the correct paths while testing.)

# Type of change📄

- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I've tested it on my own device. All the outputs are correct and the UI also matches the official app's design.

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Remove the files related to contact and 2D shapes calc first @Mannxxx

**Comment by Mannxxx** [comment]
@Rakesh9100 , Done

**Comment by Rakesh9100** [comment]
Add the `BMI-Calculator` folder under the Calculators folder and make its UI different from the main page.
Remove the navbar and footer from this calculator page.

Also add the box in the main `index.html` file for this calculator as per every calculator has the Try Now button and link that to the calculators page @Mannxxx

**Comment by Rakesh9100** [comment]
Pls add the `BMI-Calculator` folder under the Calculators folder and make its UI different from the main page.
Remove the navbar and footer from this calculator page.

Also add the box in the main `index.html` file for this calculator as per every calculator has the Try Now button and link that to the calculators page @Mannxxx

**Comment by Rakesh9100** [comment]
Are you working on the suggested changes @Mannxxx

**Comment by Mannxxx** [comment]
Yes, I'll do it by today afternoon.

**Comment by Mannxxx** [comment]
@Rakesh9100 , Done. 

image

This is how the screen looks after clicking try now:
image

**Comment by Rakesh9100** [comment]
Merged!! 🎉 @Mannxxx

**Pull request merged**
