### PR TITLE
2D Shapes Calculator

### LINKED ISSUE #2: 2D Shapes Calculator
Add a Calculator that calculates the perimeter and area of 2D shapes.

### PR DESCRIPTION
**Pull request by Mannxxx**
# Fixes Issue🛠️

Closes #2 

# Description👨‍💻 
Added 2D-shape calculator. I've imported the exact footer and header sections from the app's original index file. I've commented on where original script.js and style.css are used. (Make sure to mention the correct paths while testing.)

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I've tested it on my own device. All the outputs are correct and the UI also matches the official app's design.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
image

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls add the `2D-Shapes-Calculator` folder under the Calculators folder and make its UI different from the main page.
Remove the navbar and footer from this calculator page.

Also add the box in the main `index.html` file for this calculator as per every calculator has the Try Now button and link that to the calculators page @Mannxxx

**Comment by Rakesh9100** [comment]
Are you working @Mannxxx

**Comment by Rakesh9100** [comment]
Are you working on the mentioned changes @Mannxxx

**Comment by Mannxxx** [comment]
Yes, I'll complete it by today evening. I was busy somewhere.

**Comment by Mannxxx** [comment]
> Pls add the `2D-Shapes-Calculator` folder under the Calculators folder and make its UI different from the main page. Remove the navbar and footer from this calculator page.
> 
> Also add the box in the main `index.html` file for this calculator as per every calculator has the Try Now button and link that to the calculators page @Mannxxx

image


@Rakesh9100 , does it look fine?

**Comment by Rakesh9100** [comment]
Okay, you can commit @Mannxxx

**Comment by Rakesh9100** [comment]
Looks good, Merged!! 🎉 @Mannxxx

**Pull request merged**
